spring:
  # 配置数据源信息
  datasource:
    type:
    # 配置连接数据库信息
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://127.0.0.1:3306/mybatis_plus?characterEncoding=utf-8&useSSL=false
    username: root
    password: wxlalt

mybatis-plus:
  # 配置MyBatis日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 配置Mybatis-Plus操作表前缀
      table-prefix: t_
      # 配置MyBatis-Plus的主键策略
      id-type: auto
  # 配置扫描通用枚举
  type-enums-package: com.wxl52d41.mybatis_plus.enums
#  mapper-locations: classpath:com/wxl52d41/mybatis_plus/mapper/*.xml
#  type-aliases-package: com.wxl52d41.mybatis_plus.entity