server:
  port: 8079

spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: u_std_ads_pre
    password: aDsPre#test123
    driverClassName: oracle.jdbc.driver.OracleDriver


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/example/demo/mapper/**/*.xml
  type-aliases-package: com.example.demo.entity